name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20.18.1
  PNPM_VERSION: 9.15.3

jobs:

  run-migrations:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ env.NODE_VERSION }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ env.NODE_VERSION }}-

      - name: Cache pnpm dependencies
        shell: bash
        run: pnpm fetch --store-dir ~/.pnpm-store

      - name: Copy env
        shell: bash
        run: |
          echo "${{ secrets.ENV }}" >> .env

      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile --store-dir ~/.pnpm-store
        
      - name: Run migrations
        run: pnpm db:migrate